create database DPA;
use DPA;
create table Doctor (docid int primary key ,Dname varchar(30),phone varchar(15),special varchar(30),uname varchar(30),password varchar(30));
create table Patient (patid int primary key,Pname varchar(30),phone varchar(15),uname varchar(30),password varchar(30));
create table Appointment1(atime date,docid int,foreign key fk1(docid) references Doctor(docid),patid int,foreign key fk2(docid) references Patient(patid), primary key(docid,atime));
select * from Doctor;
select * from Patient;
insert into Doctor value(1,'akshay','3322','eye','akshay','8600723121');
show tables;
insert into Doctor value(2,'akshay','3322','Nose','akshay123','8600723121');
insert into Patient value(1,'shivam','2353','shivam','javacjavac');
Describe Doctor;
alter table Doctor modify column docid int auto_increment;
alter table Patient modify column patid int auto_increment;
alter table Doctor change special special varchar(30) after password;
alter table Appointment1 add problem varchar(50);
alter table Appointment1 modify column atime timestamp;
delete from Appointment1;
describe Appointment1;
select * from Doctor,Patient,Appointment1 where Doctor.docid=Appointment1.docid and Patient.patid=Appointment1.patid;
select Patient.pname,Patient.phone,atime,problem,done from Doctor,Patient,Appointment1 where Doctor.docid=Appointment1.docid and Patient.patid=Appointment1.patid and month(curdate())=month(atime) and year(curdate())=year(atime) and Doctor.docid=1;
select Patient.pname,Patient.phone,atime,problem,done from Doctor,Patient,Appointment1 where Doctor.docid=Appointment1.docid and Patient.patid=Appointment1.patid and month(curdate())=month(atime) and year(curdate())=year(atime) and day(ADDDATE(curdate(),-1))=day(atime) and Doctor.docid=1;
create table Apprequest (patid int,foreign key fk1(patid) references Patient(patid),patname varchar(30),docid int,foreign key fk2(docid) references Doctor(docid),Preblem varchar(30),pnone varchar(30),ptime timestamp);
describe Apprequest;
select * from Apprequest;
select * from Appointment1;
select pname,preblem from Apprequest where docid=1 and ptime='20160229190000';
describe Appointment1;
alter table Appointment1 change Done Phone varchar(30);
insert into Appointment1 value ('20160304090000',1,1,'yiut','3456789');
insert into Appointment1 value ('20160301010000',1,1,'boom','234567');
insert into Appointment1 value ('null',1,1,'boom','234567');
insert into Appointment1 value ('2016-03-01 01:00:00.0',1,1,'boom','234567');
select patname,preblem,patid,pnone,ptime from Apprequest where docid=1;
insert into Appointment1 value ('2016-03-01 01:00:00.0',1,1,'boom','234567');
select * from Apprequest,Doctor where Apprequest.docid=Doctor.docid patid=1;